export const UsersSchema = {
    tableName: 'users',
    columns: {
      id: { type: 'VARCHAR(255)', primary: true, nullable: false },
      name: { type: 'VARCHAR(255)', nullable: false },
      email: { type: 'VARCHAR(255)', unique: true, nullable: false },
      password: { type: 'VARCHAR(255)', nullable: false },
      balance: { type: 'INT', nullable: false, default: 0 },
      latitude: { type: 'DECIMAL(10,8)', nullable: true },
      longitude: { type: 'DECIMAL(11,8)', nullable: true },
      isBlocked: { type: 'TINYINT(1)', nullable: false, default: 0 },
      createdAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
      updatedAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        onUpdate: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
    },
  };
  
  export const BikesSchema = {
    tableName: 'bikes',
    columns: {
      id: { type: 'VARCHAR(255)', primary: true, nullable: false },
      bikeNumber: { type: 'INT', unique: true, nullable: false },
      latitude: { type: 'DECIMAL(10,8)', nullable: false },
      longitude: { type: 'DECIMAL(11,8)', nullable: false },
      isFaulty: { type: 'TINYINT(1)', nullable: false, default: 0 },
      status: { type: 'VARCHAR(50)', nullable: false, default: 'available' },
      bikeCategory: { type: 'VARCHAR(50)', nullable: true },
      createdAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
      updatedAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        onUpdate: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
    },
  };
  
  export const ServiceAreasSchema = {
    tableName: 'service_areas',
    columns: {
      id: { type: 'INT', primary: true, nullable: false, autoIncrement: true },
      name: { type: 'VARCHAR(100)', nullable: true },
      area: { type: 'POLYGON', nullable: false, spatial: true, indexed: true },
      city_id: { type: 'BIGINT', nullable: false, indexed: true },
    },
  };
  
  export const ServicesSchema = {
    tableName: 'services',
    columns: {
      id: { type: 'BIGINT', primary: true, nullable: false, autoIncrement: true },
      name: { type: 'VARCHAR(255)', unique: true, nullable: false },
      createdAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
      updatedAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        onUpdate: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
    },
  };
  
  export const BikeAvailabilityHistorySchema = {
    tableName: 'bikeAvailabilityHistory',
    columns: {
      id: { type: 'VARCHAR(255)', primary: true, nullable: false },
      userId: { type: 'VARCHAR(255)', nullable: false, indexed: true },
      searchTime: {
        type: 'TIMESTAMP',
        nullable: false,
        default: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
      latitude: { type: 'DECIMAL(10,8)', nullable: false },
      longitude: { type: 'DECIMAL(11,8)', nullable: false },
      response: { type: 'JSON', nullable: true },
    },
  };

  export const CitiesSchema = {
    tableName: 'cities',
    columns: {
      id: { type: 'BIGINT', primary: true, nullable: false, autoIncrement: true },
      name: { type: 'VARCHAR(255)', nullable: false },
      centroidLatitude: { type: 'DECIMAL(10,8)', nullable: false },
      centroidLongitude: { type: 'DECIMAL(11,8)', nullable: false },
      activeServiceIds: { type: 'JSON', nullable: true },
      createdAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
      updatedAt: {
        type: 'TIMESTAMP',
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        onUpdate: 'CURRENT_TIMESTAMP',
        autoGenerated: true,
      },
    },
  };
  
  